version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_SERVLET_CONTEXT_PATH: /transfer-system
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/bank
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
